### ISSUE TITLE
BackGroundReplacementApp

### ISSUE THREAD

**Issue by pratapic5** [fritzlabs/fritz-android-tutorials#33]
Thank you for great Library.

When i run BackGroundReplacementApp .I granted permission and then open app crashing every time 

//LOG 

 Process: ai.fritz.backgroundChanger, PID: 26521
    java.lang.RuntimeException: Unable to start activity ComponentInfo{ai.fritz.backgroundChanger/ai.fritz.replaceBackground.MainActivity}: java.lang.RuntimeException: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
        at ai.fritz.customtflite.FritzTFLiteInterpreter.<init>(FritzTFLiteInterpreter.java:40)
        at ai.fritz.vision.base.FritzVisionTFLitePredictor.<init>(FritzVisionTFLitePredictor.java:26)
        at ai.fritz.vision.base.FritzVisionTFLitePredictor.<init>(FritzVisionTFLitePredictor.java:21)
        at ai.fritz.vision.imagesegmentation.FritzVisionSegmentTFLPredictor.<init>(FritzVisionSegmentTFLPredictor.java:39)
        at ai.fritz.vision.imagesegmentation.FritzVisionSegmentPredictor.<init>(FritzVisionSegmentPredictor.java:9)
        at ai.fritz.vision.FritzVision$ImageSegmentationFeature.getPredictor(FritzVision.java:71)
        at ai.fritz.replaceBackground.MainActivity.onCreate(MainActivity.java:68)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
        at android.content.res.AssetManager.nativeOpenAssetFd(Native Method)
        at android.content.res.AssetManager.openFd(AssetManager.java:768)
        at ai.fritz.core.FritzOnDeviceModel.readModelFile(FritzOnDeviceModel.java:164)
        at ai.fritz.customtflite.FritzTFLiteInterpreter.<init>(FritzTFLiteInterpreter.java:37)
        at ai.fritz.vision.base.FritzVisionTFLitePredictor.<init>(FritzVisionTFLitePredictor.java:26) 
        at ai.fritz.vision.base.FritzVisionTFLitePredictor.<init>(FritzVisionTFLitePredictor.java:21) 
        at ai.fritz.vision.imagesegmentation.FritzVisionSegmentTFLPredictor.<init>(FritzVisionSegmentTFLPredictor.java:39) 
        at ai.fritz.vision.imagesegmentation.FritzVisionSegmentPredictor.<init>(FritzVisionSegmentPredictor.java:9) 
        at ai.fritz.vision.FritzVision$ImageSegmentationFeature.getPredictor(FritzVision.java:71) 
        at ai.fritz.replaceBackground.MainActivity.onCreate(MainActivity.java:68) 
        at android.app.Activity.performCreate(Activity.java:7136) 
        at android.app.Activity.performCreate(Activity.java:7127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-06-13 15:35:36.121 26521-26565/ai.fritz.backgroundChanger D/PostRequestTask: Api Request: https://api.fritz.ai/sdk/v1/model/track

**Comment by hsiaoer** [comment]
@pratapic5 thanks for letting us know! I just fixed this issue by setting the noCompress option: https://github.com/fritzlabs/fritz-android-tutorials/blob/master/BackgroundReplacementApp/app/build.gradle#L24

**Comment by pratapic5** [comment]
Thank you for support.

https://github.com/fritzlabs/fritz-android-tutorials/issues/33

- crash is resolve now but still it will not showing anything in the screen.show only white screen 

Please refer mention link screenshot :

https://drive.google.com/file/d/1n1_8b3M1aGLdmEnhVuPnuM2LBTjlNLEt/view

Device Configuration:

**0 ) Samsung edge s7
1 ) Model : SM-G935FD
2 ) Oreo  
3 ) Version : 8.0.0**

**Comment by hsiaoer** [comment]
Ah, that's a permission issue I just fixed up. Try it out now and let me know if you still see that.

**Comment by pratapic5** [comment]
Thanks for fixing issues  Earic,
BackgroundReplacementApp working fine now.

-one more question about the BackgroundReplacementApp
is there any way to input Image load from sdcard instead of  camera capture ?
Thanks,
Pratap
